# Generated by Django 5.1.1 on 2025-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='books_in_bag',
            field=models.ManyToManyField(related_name='reader_bag', to='api.book'),
        ),
    ]
